networks:
  demo:
    driver: bridge

services:

  mailpit:
    image: axllent/mailpit:v1.18.3
    container_name: mailpit
    restart: on-failure
    ports:
      - 8025:8025 # HTTP
      - 1025:1025 # SMTP
    environment:
      TZ: Europe/Lisbon
    networks:
      - demo
