apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    readOnly: false
    jsonData:
      #httpMethod: POST
      httpMethod: GET


  # https://grafana.com/docs/grafana/next/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
  - name: Tempo
    type: tempo
    uid: tempo-uid
    access: proxy
    url: http://tempo:3200
    isDefault: false
    readOnly: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: loki-uid
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        #tags: ['job', 'instance', 'pod', 'namespace']
        filterByTraceID: true
        filterBySpanID: true
        customQuery: true
        query: 'method="$${__span.tags.method}"'
      tracesToMetrics:
        datasourceUid: prometheus-uid
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        # tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      tracesToProfiles:
        datasourceUid: pyroscope-uid
        customQuery: true
      serviceMap:
        datasourceUid: prometheus-uid
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
      # spanBar:
      #   type: 'Tag'
      #   tag: 'http.path'


  - name: Loki
    type: loki
    uid: loki-uid
    access: proxy
    url: http://loki:3100
    isDefault: false
    readOnly: false
    jsonData:
      derivedFields:
      - datasourceUid: tempo-uid # To link traceId to Tempo
        matcherRegex: "\"[tT][rR][aA][cC][eE][iI][dD]\":\"(\\w+)\""
        name: "TraceId"
        url: "$${__value.raw}"


  - name: Alertmanager
    type: alertmanager
    uid: alertmanager-uid
    access: proxy
    url: alertmanager:9093
    isDefault: false
    readOnly: false
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true # Alertmanager will handle alerts created by Grafana


  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope-uid
    access: proxy
    url: http://pyroscope:4040
    isDefault: false
    readOnly: false
    jsonData:
      minStep: '15s'
